# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - ml-service
    networks:
      - sceneshield-network

  ml-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.ml-service
    ports:
      - "5000:5000"
    networks:
      - sceneshield-network

networks:
  sceneshield-network:
    driver: bridge
